version: '3.3'

services:
  postgresql:
    image: postgres:12.8-alpine
    #    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      #      - POSTGRESQL_PASSWORD=pass
      - POSTGRES_USER=app
      #      - POSTGRESQL_USERNAME=app
      - POSTGRES_DB=job1
    #      - POSTGRESQL_DB=marketdb
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - job

networks:
  job:
    driver: bridge